return {}
-- return {
-- 'akinsho/toggleterm.nvim',
-- version = "*",
-- config = function()
--   require("toggleterm").setup({
--     open_mapping = [[<c-\>]],
--     hidenumbers = true,
--     direction = "float",
--   })
-- end
-- }
